# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='show/hide record.', verbose_name='enabled')),
                ('pub_date_start', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Rocord will be visible form this date.', verbose_name='start date for publication')),
                ('pub_date_end', models.DateTimeField(blank=True, db_index=True, help_text='Rocord will be invisible form this date.', null=True, verbose_name='end date for publication')),
                ('weight', models.PositiveIntegerField(db_index=True, default=0, help_text='Rocord will be first with greate weight.', verbose_name='weight of publication')),
                ('title', models.CharField(max_length=255, verbose_name='contact title')),
                ('content', models.TextField(verbose_name='contact content')),
            ],
            options={
                'ordering': ['-weight', '-pub_date_start'],
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
