# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.CharField(max_length=255, verbose_name='tariff price'),
        ),
    ]
