# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0002_auto_20160528_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='user fio')),
                ('contact', models.CharField(max_length=255, verbose_name='user contact')),
                ('address', models.CharField(max_length=255, verbose_name='user address')),
                ('answered', models.BooleanField(default=False, verbose_name='answered')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariff.Tariff', verbose_name='tariff')),
            ],
            options={
                'ordering': ['-create_date'],
                'verbose_name': 'connect request item',
                'verbose_name_plural': 'connect request items',
            },
        ),
    ]
